const googlemodel = require('@google/genai').GoogleGenAI
const express = require('express')
const cors = require('cors')

require('dotenv').config()


const app = express()
app.use(cors())
app.use(express.json())

const ai = new googlemodel({apiKey : process.env.API_KEY})
let chat_history = []


app.post('/query', async (req, res) => {

    chat_history.push({
        query : req.body.query,
        content_response : "",
        index : chat_history.length,
    })

    let content_prompt = ` You will receive an array representing the complete chat history.

Each item in the array contains:

index → the message order
user_prompt → the message sent by the user
assistant_response → the response generated by the assistant

Treat the entire array as one continuous conversation, maintaining context across all entries.

Rules:

The item with the highest index represents the latest interaction.
Use previous messages to understand context, references, follow-up questions, and conversation flow.
Respond primarily to the latest user_prompt, while considering all earlier conversation history.
Do not treat messages independently; interpret them as part of a single ongoing chat session.
Preserve conversational continuity, memory, and tone consistency when generating responses.
Your task: Analyze the entire conversation history and generate the next assistant response for the latest user message.

This is the array : 
${JSON.stringify(chat_history)}
`

    const response = await ai.models.generateContent({
        model : "gemini-3.5-flash",
        contents : content_prompt,
        
    })


        res.json({'reply' : response.text})
        chat_history[chat_history.length - 1]['content_response'] = response.text

    })


app.listen(3000, () => {
    console.log("Server is running on port 3000")
})